/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pEZdPb88zvW8NfciQQQwSK

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantskIpj09IbynjR } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: KIpj09ibynjR/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantskIpj09IbynjR
});
