/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
import {
  REST_DELETE,
  REST_GET,
  REST_OPTIONS,
  REST_PATCH,
  REST_POST,
  REST_PUT,
} from '@payloadcms/next/routes'

export const DELETE = REST_DELETE
export const GET = REST_GET
export const OPTIONS = REST_OPTIONS
export const PATCH = REST_PATCH
export const POST = REST_POST
export const PUT = REST_PUT
